export const FETCH_ASSIGNED_CPP_TEST_COUNT = 'FETCH_ASSIGNED_CPP_TEST_COUNT';
export const FETCH_ASSIGNED_CPP_TEST_LIST = 'FETCH_ASSIGNED_CPP_TEST_LIST';
export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST';
export const FETCH_STUDENT_SUMMARY = 'FETCH_STUDENT_SUMMARY';

// Test evaluation actionTypes
export const ASSIGNED_MARKS = 'ASSIGNED_MARKS';
export const MODIFY_ORIGINAL_QUESTIONS = 'MODIFY_ORIGINAL_QUESTIONS';
export const ANNOTATED_PDF = 'ANNOTATED_PDF';
export const RESET_UNSAVED_CHANGES = 'RESET_UNSAVED_CHANGES';
export const SYNC_EVALUATION = 'SYNC_EVALUATION';
export const SUBMIT_EVALUATION = 'SUBMIT_EVALUATION';
export const FETCH_TEACHERS_PDF = 'FETCH_TEACHERS_PDF';
export const RESPONSE_MESSAGES = 'RESPONSE_MESSAGES';
export const SET_SUBMIT_SUMMARY = 'SET_SUBMIT_SUMMARY';
export const TOGGLE_SUBMIT_SUMMARY = 'TOGGLE_SUBMIT_SUMMARY';

// PDF sketch Related actionTypes
export const INITIALISE_PDF_SKETCH = 'INITIALISE_PDF_SKETCH';
export const SET_SKETCH_TOOL = 'SET_SKETCH_TOOL';
export const FETCH_PDF_AND_LOAD_PAGES = 'FETCH_PDF_AND_LOAD_PAGES';
export const LOAD_PDF_PAGES = 'LOAD_PDF_PAGES';
export const MODIFY_PDF_PAGE = 'MODIFY_PDF_PAGE';
export const ZOOM_IN = 'ZOOM_IN';
export const ZOOM_OUT = 'ZOOM_OUT';
export const UNDO = 'UNDO';
export const REDO = 'REDO';
export const NAVIGATE_TO_PDF_PAGE = 'NAVIGATE_TO_PDF_PAGE';
export const NAVIGATE = 'NAVIGATE';
export const STORE_SNAPSHOT_OF_CURRENT_PDP_PAGE =
  'STORE_SNAPSHOT_OF_CURRENT_PDP_PAGE';
export const CLEAR_PDF_PAGE = 'CLEAR_PDF_PAGE';
export const MODIFY_SCALE = 'MODIFY_SCALE';
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN';
