export const FETCH_STUDENT_LIST_BY_KEYWORD = 'FETCH_STUDENT_LIST_BY_KEYWORD';
export const FETCH_STUDENT_PROFILE_SUMMARY = 'FETCH_STUDENT_PROFILE_SUMMARY';
export const FETCH_STUDENT_ASSIGNMENTS = 'FETCH_STUDENT_ASSIGNMENTS';
export const FETCH_STUDENT_CONCEPTS = 'FETCH_STUDENT_CONCEPTS';
export const FETCH_STUDENT_RECENT_SEARCH_LIST =
  'FETCH_STUDENT_RECENT_SEARCH_LIST';
export const ADD_STUDENT_SEARCH_EVENT = 'ADD_STUDENT_SEARCH_EVENT';
