export const FETCH_CPP_TESTS = `FETCH_CPP_TESTS`;
export const FETCH_ASSIGNMENT_HISTORY = `FETCH_ASSIGNMENT_HISTORY`;
export const FETCH_BATCH_STUDENTS = `FETCH_BATCH_STUDENTS`;
export const FETCH_BATCH_SUMMARY = 'FETCH_BATCH_SUMMARY';
export const FETCH_BATCH_STUDENT_LIST = 'FETCH_BATCH_STUDENT_LIST';
export const CPP_ASSIGN_TEST = 'CPP_ASSIGN_TEST';
export const FETCH_CPP_TEST_DETAILS = `FETCH_CPP_TEST_DETAILS`;

export const CPP_SNACKBAR = 'CPP_SNACKBAR';
